name: repository
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.0
  iod: ^0.0.3
  equatable: ^2.0.8
  common_models:
    path: ../common_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mock_supabase_http_client: ^0.0.3
  mockito: ^5.6.1
  build_runner: ^2.4.6


flutter: